# This workflow will install dependencies, create coverage tests and run Jest Coverage Comment

name: Jest Coverage Report
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npx jest --coverage --coverageReporters json-summary --silent

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Jest Coverage report
          badge-title: Coverage
          hide-comment: false
          create-new-comment: true
          hide-summary: false
